name: Build and Push

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: whoami
  ECR_REGISTRY: 719572784863.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: |
          docker build \
          -t $ECR_REPOSITORY:${{ github.sha }} .

      - name: Tag Image
        run: |
          docker tag \
          $ECR_REPOSITORY:${{ github.sha }} \
          $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      - name: Push Image
        run: |
          docker push \
          $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}